Repository TheBestTvarynka/ubiquitous-spark, pull requests merged in 2019-12, with the labels that each got.

#12 Chat
  .gitignore
  db/dbreader.js
  img/loading.gif
  index.js
  package-lock.json
  package.json
  routing/chat.js
  site/stylesheets/chat.css
  site/stylesheets/chat_entry.css
  site/views/chat.hbs
  site/views/chat_entry.hbs
Labels: feature

#13 Finished homepage
  index.js
  routing/search.js
  site/stylesheets/home.css
  site/views/home.hbs
Labels: feature

#15 Smaill improvments
  db/dbreader.js
  index.js
  routing/books.js
  routing/chat.js
  routing/search.js
  site/default.hbs
  site/views/account/account.hbs
  site/views/account/likedbooks.hbs
  site/views/account/mybooks.hbs
  site/views/addbook.hbs
  site/views/chat.hbs
  site/views/chat_entry.hbs
Labels: feature, fix

#14 Added small fixes...
  routing/account.js
  routing/chat.js
  site/stylesheets/chat.css
  site/views/account/account.hbs
  site/views/chat_entry.hbs
Labels: fix
